# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studygroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='studygroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.StudyGroup'),
        ),
    ]
