# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_userprofile_studygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateTimeField(),
        ),
    ]
