# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_resutl_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
