# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_auto_20170504_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('filePath', models.CharField(default='', max_length=100)),
                ('rightAnswers', models.IntegerField(default=0)),
                ('wrongAnswers', models.IntegerField(default=0)),
                ('isVisible', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='resutl',
            name='user',
        ),
        migrations.DeleteModel(
            name='Resutl',
        ),
    ]
