# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170512_1206'),
        ('tests', '0006_auto_20170504_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsettings',
            name='studygroup',
            field=models.ManyToManyField(to='students.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='testsettings',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.Subject'),
        ),
    ]
