# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170512_1206'),
        ('tests', '0007_auto_20170512_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsettings',
            name='studygroup',
        ),
        migrations.RemoveField(
            model_name='testsettings',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='publicResults',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='studygroup',
            field=models.ManyToManyField(to='students.StudyGroup'),
        ),
        migrations.DeleteModel(
            name='TestSettings',
        ),
    ]
