# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20170513_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='tests.Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
