# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20170513_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.Subject'),
        ),
    ]
