# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_remove_result_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.IntegerField(default=0)),
                ('all', models.IntegerField(default=0)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.Subject')),
            ],
        ),
    ]
