# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_testsstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='studygroup',
            field=models.ManyToManyField(related_name='groups', to='students.StudyGroup'),
        ),
    ]
